### ISSUE TITLE
Text field/Input possible cleanup

### ISSUE THREAD

**Issue by phated** [samrocksc/react-material-design-lite#14]
I don't think the label and error element shouldn't be generated inside the component based on props, instead they should probably be separate components that you nest (?) inside the TextField element.

It might also make sense to split out TextArea.

A problem that you might run into is the wrapper div around the 3 elements, not sure how to solve that technically.

Example of usage:

```
<label htmlFor="yourid">Some text</label>
<input id="yourid" />
```

should be exchangeable with:

```
<TextFieldLabel htmlFor="yourid">Some text</TextFieldLabel>
<TextField id="yourid" />
```

**Comment by samrocksc** [comment]
Here is proposed:

```
<Textfield expandable>
  <TextFieldInput />
  <TextFieldLabel>label here</TextFieldLabel>
  <TextFieldError>Error here</TextFieldError>
</Textfield>
```

The issue at hand is how to force an element to inherit a prop for id and for.  Any thoughts?

**Comment by phated** [comment]
If we have to use a container element, the container should be named `TextFieldContainer` instead of `TextField`
